#!/bin/bash

STREAMING_CHUNK:Initializing standard YunoHost installation helpers...

source /usr/share/yunohost/helpers
ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
install_dir="/var/www/$app"

ynh_print_info --message="Setting up system user and directories..."
ynh_system_user_create --username=$app
mkdir -p "$install_dir"

STREAMING_CHUNK:Setting up PostgreSQL database automatically...

ynh_print_info --message="Provisioning PostgreSQL database..."
ynh_pgsql_setup_db

Note: ynh_pgsql_setup_db sets the variable $db_pwd automatically

ynh_print_info --message="Installing PHP dependencies..."
ynh_install_app_dependencies php-fpm php-pgsql

STREAMING_CHUNK:Copying web assets and injecting database credentials...

ynh_print_info --message="Copying web files..."
cp -a ../src/* "$install_dir/"

ynh_print_info --message="Injecting database credentials into API..."
ynh_replace_string --match_string="DB_HOST" --replace_string="127.0.0.1" --target_file="$install_dir/api.php"
ynh_replace_string --match_string="DB_NAME" --replace_string="$app" --target_file="$install_dir/api.php"
ynh_replace_string --match_string="DB_USER" --replace_string="$app" --target_file="$install_dir/api.php"
ynh_replace_string --match_string="DB_PWD" --replace_string="$db_pwd" --target_file="$install_dir/api.php"

chown -R $app: "$install_dir"

STREAMING_CHUNK:Finalizing web server configuration and restarting services...

ynh_print_info --message="Configuring PHP-FPM..."
ynh_php_version_default="8.2"
ynh_use_php
ynh_add_fpm_config

ynh_print_info --message="Configuring NGINX..."
ynh_add_nginx_config

systemctl reload nginx
systemctl reload php${YNH_PHP_VERSION}-fpm

ynh_print_info --message="Connections clone successfully installed!"
